# -*- coding: utf-8 -*-
"""TechChallenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dw_ryzmqpMtL_Kxu52zsWTUt-rCXQKBs

# Tech Challenge

Analisar o desempenho operacional e comercial da Olist com foco em melhorar a receita e a experiência do cliente. Baseado em dados do Kaggle.com entre setembro de 2016 a  outubro de 2018, identificando padrões de consumo, eficiência logística e o comportamento do marketplace brasileiro para subsidiar decisões estratégicas de expansão e qualidade de serviço.

## Introdução

O perido de 2016 a 2018 foi marcado pela consolidadação da Olist como um hub fundamental de conexão entre pequenos varejistas e grandes marketplaces brasileiros. A empresa demonstrou alto crescimento no volume de vendas (GMV).
A logística demonstrou ser um ponto crítico. com melhorias focadas na redução do tempo de entrega para atender às demandas dos marketplaces e clientes finais.
"""
Links importantes: https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce
                   https://pandas.pydata.org/


# importar bibliotecas Python

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# carregando dados - Dataset

orderes = pd.read_csv('olist_orders_dataset.csv')
payments = pd.read_csv('olist_order_payments_dataset.csv')
reviews = pd.read_csv('olist_order_reviews_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
sellers = pd.read_csv('olist_sellers_dataset.csv')

# unindo tabelas e tratando datas

df_vendas = pd.merge(orderes, payments, on='order_id')
df_vendas['order_purchase_timestamp'] = pd.to_datetime(df_vendas['order_purchase_timestamp'])
df_vendas['mes_ano'] = df_vendas['order_purchase_timestamp'].dt.to_period('M')

# Agrupando receita por mês

receita_mensal = df_vendas.groupby('mes_ano')['payment_value'].sum()

plt.figure(figsize=(12, 6))
receita_mensal.plot(title='Evolução da Receita Mensal')
plt.xlabel('Mês e Ano')
plt.ylabel('Receita Total')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Gráfico mostrando a evolução da receita mensal.Pode observar que as operações tiveram um inicio modesto em 2016, porém apresentou uma curva de crescimento acelerado ao longo de 2017. O pico no final do ano coincide com a Black Friday, demonstrando que a plataforma tem alta tração em enventos promocionais. A tendência é de alta,o que valida o modelo de mercado."""

# calculando tempo de entrega real e atrasos

orderes['order_delivered_customer_date'] = pd.to_datetime(orderes['order_delivered_customer_date'])
orderes['order_estimated_delivery_date'] = pd.to_datetime(orderes['order_estimated_delivery_date'])
orderes['order_purchase_timestamp'] = pd.to_datetime(orderes['order_purchase_timestamp'])

# Dias para entregar

orderes['dias_entrega'] = orderes['order_delivered_customer_date'] - pd.to_datetime(orderes['order_purchase_timestamp'])

# Convertendo Timedelta para dias numéricos para plotagem
orderes['dias_entrega_numerico'] = orderes['dias_entrega'].dt.days

# Gráfico de densidade do tempo de entrega

plt.figure(figsize=(10, 5))
sns.histplot(orderes['dias_entrega_numerico'].dropna(), bins=50, kde=True, color='blue')
plt.title('Distribuição do tempo de entrega (Dias)')
plt.xlabel('Dias até o cliente receber o produto')
plt.ylabel('Densidade')
plt.show()

"""O Grafico demonstra os dias de entrega e gerou um gráfico de densidade (histograma) mostrando a distribuição do tempo de entrega em dias."""

# Meios de pagamento

customers = pd.read_csv('olist_customers_dataset.csv')

sns.countplot(data=payments, x='payment_type', order=payments['payment_type'].value_counts().index)
plt.title('Distribuição por Meio de Pagamento')
plt.show()

"""O gráfico de distribuição por meio de pagamento. Ele mostra os diferentes tipos de pagamento utilizados pelos clientes e a frequência de cada um.Aproximadamente 75% das transações são feitas com cartão de crédito. Isso mostra que o cliente prefere o parcelamento. Pode-se pensar em estratégias para diminuir a dependência das taxas das operadoras de cartão com incentivos para pagamento por pix, cashback poderiam melhorar o fluxo de caixa."""

# Top 10 estados

# Distruibuição Geográfica (Top 10 Estados)
geo_dist = customers['customer_state'].value_counts().head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=geo_dist.values, y=geo_dist.index, color='Teal')
plt.title('Top 10 Estados com Mais Clientes')
plt.ylabel('Estado')
plt.xlabel('Número de Clientes')
plt.show()

"""O gráfico mostrando os Top 10 Estados com Mais Clientes foi gerado e exibido com sucesso. Você pode ver a distribuição geográfica dos seus clientes."""

# Faturamento Mensal

df_vendas = pd.merge(orderes, payments, on='order_id')
df_vendas['order_purchase_timestamp'] = pd.to_datetime(df_vendas['order_purchase_timestamp'])
df_vendas['mes_ano'] = df_vendas['order_purchase_timestamp'].dt.to_period('M')
receita_mensal = df_vendas.groupby('mes_ano')['payment_value'].sum()

plt.figure(figsize=(12, 6))
plt.plot(receita_mensal.index.astype(str), receita_mensal)
plt.title('Faturamento Mensal')
plt.xlabel('Mês e Ano')
plt.ylabel('Receita Total')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""O gráfico mostra a evolução da receita total ao longo dos meses e anos, permitindo visualizar as tendências de vendas."""

# Unindo DataFrames de pedidos e avaliações
df_entrega_avaliacao = pd.merge(orderes[['order_id', 'dias_entrega_numerico']], reviews[['order_id', 'review_score']], on='order_id', how='inner')

# Removendo valores nulos para a análise de correlação
df_entrega_avaliacao.dropna(subset=['dias_entrega_numerico', 'review_score'], inplace=True)

# Calculando a correlação de Pearson
correlation = df_entrega_avaliacao['dias_entrega_numerico'].corr(df_entrega_avaliacao['review_score'])

print(f"Correlação entre Tempo de Entrega e Nota de Avaliação: {correlation:.2f}")

# Visualizando a relação com um gráfico de dispersão
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_entrega_avaliacao, x='dias_entrega_numerico', y='review_score', alpha=0.5)
plt.title('Relação entre Tempo de Entrega e Nota de Avaliação')
plt.xlabel('Dias para Entrega')
plt.ylabel('Nota de Avaliação (1-5)')
plt.grid(True)
plt.show()

""" Análise da Correlação entre Tempo de Entrega e Nota das Avaliações

A análise de correlação entre o tempo de entrega e a nota das avaliações foi concluída. A correlação de Pearson calculada foi de -0.33. Isso sugere uma correlação negativa moderada, o que significa que, em geral, quanto maior o tempo de entrega, menor a nota de avaliação dos clientes.

O gráfico de dispersão também mostra essa tendência, onde a concentração de pontos se desloca para notas mais baixas à medida que o tempo de entrega aumenta. Clientes que recebem seus produtos mais rapidamente tendem a dar avaliações mais altas.
"""

